name: bookbinder

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2-beta
      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Install system dependencies
        run: |
          sudo apt install -y minify

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install markdown jinja2 pygments pyyaml
          echo "::set-env name=PYTHONPATH::/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages"
          sudo ln -sf $(which python) /usr/bin/python3

      - name: Install Go dependencies
        run: |
          go get -v github.com/dreadl0ck/zeus@45d665d962
          echo "::add-path::$(go env GOPATH)/bin"
        env:
          GO111MODULE: on

      - name: Generate website
        run: |
          zeus wikis
          zeus generate
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: davidepucci
          path: public/*