name: bookbinder

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Install system dependencies
        run: |
          sudo apt install -y minify

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install markdown jinja2 pygments pyyaml requests
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV
          sudo ln -sf $(which python) /usr/bin/python3

      - name: Generate website
        run: |
          make
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: davidepucci
          path: build/*

      - name: Publish website
        run: |
          make publish
        env:
          PUB_KEY: ${{ secrets.GH_ACTIONS_SSH_KEY }}