name: monk

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_DAVIDEPUCCI }}

      - name: Setup repository
        run: |
          git config user.email "monk@davidepucci.it" 
          git config user.name "Amanuensis Monk"

      - name: Run packages update check
        run: |
          make wikis
          if ! git diff-index --quiet HEAD -- src/wikis; then
            git commit -m "src: wikis: flush" src/wikis
          fi
          git push